<?xml version="1.0" encoding="utf-8"?><Database Name="model" Class="TransportLinkDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=AMESHPC\AMESHK_SERVER;Initial Catalog=model;Persist Security Info=True;User ID=sa" SettingsObjectName="Order_System_UI.Properties.Settings" SettingsPropertyName="modelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TransportationDataLog" Member="TransportationDataLog1s">
    <Type Name="TransportationDataLog1">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Name of Seller]" Member="Name_of_Seller" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Truck Company]" Member="Truck_Company" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Quality" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Number of Bags]" Member="Number_of_Bags" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Freight Charges]" Member="Freight_Charges" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Shipment Number]" Member="Shipment_Number" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Date of Arrival]" Member="Date_of_Arrival" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Total Cost]" Member="Total_Cost" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>