<?xml version="1.0" encoding="utf-8"?><Database Name="model" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=AMESHPC\AMESHK_SERVER;Initial Catalog=model;User ID=sa" SettingsObjectName="CottonOilFactory.OrderSystemGUI.Properties.Settings" SettingsPropertyName="modelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TransportationDatum" Member="TransportationDatums">
    <Type Name="TransportationDatum">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Name of Seller]" Member="Name_of_Seller" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Truck Company]" Member="Truck_Company" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Quality" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Number of Bags]" Member="Number_of_Bags" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Freight Charges]" Member="Freight_Charges" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Shipment Number]" Member="Shipment_Number" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Date of Arrival]" Member="Date_of_Arrival" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Total Cost]" Member="Total_Cost" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SalesDatum" Member="SalesDatums">
    <Type Name="SalesDatum">
      <Column Name="SalesDatumID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Name of Buyer]" Member="Name_of_Buyer" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Weight per Bag]" Member="Weight_per_Bag" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Price per Bag]" Member="Price_per_Bag" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Number of Bags]" Member="Number_of_Bags" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Total Cost]" Member="Total_Cost" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Payment Method]" Member="Payment_Method" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="[Date of Sale]" Member="Date_of_Sale" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>